INDIGO_WELCOME_MESSAGE: "Courses for researchers"
INDIGO_PRIMARY_COLOR: "#3b85ff" # cool blue

INDIGO_FOOTER_NAV_LINKS:
  - title: "About"
    url: "https://iknito.ca/about-us-and-iknito/"
  - title: "Contact us"
    url: "https://iknito.ca/contact-us/"
INDIGO_FOOTER_LEGAL_LINKS:
  - title: "Terms of service"
    url: "https://iknito.ca/terms-and-conditions/"
  - title: "Privacy Policy"
    url: "https://iknito.ca/privacy-policy/"
  - title: "© 2021 Notion Wave Inc."
    url: "https://notionwave.ca/"